### ISSUE TITLE
Unable to change my profile picture

### ISSUE THREAD

**Issue by Sakdow** [Jeroli-co/Cheddarr#35]
**Describe the bug**
Unable to change my profile picture.

**To Reproduce**
1. Go to your profile settings.
2. Click on your profile picture.
3. Select the image you want to upload.
4. Click on "open".

**Expected behavior**
Change your profile picture

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome
 - Version :  80.0.3987.149 (64 bits)

**Comment by Olived-fr** [comment]
fixed in 919a23ffc423557fcc4d2e7a226cbd5777c65268
